import CustomErro from './CustomError';

class NotFoundException extends CustomErro {

    constructor(message: string = 'Dado n√£o encontrado'){
        super(message,404);
    }
}

export default NotFoundException;